---
title: "parse_ores"
author: "Anirudh"
date: "2022-10-10"
output: html_document
---

```{r setup}

library(dplyr)
library(tidyr)
library(stringr)
```

```{r}

ores<- read.csv("mineral-ores.csv")

ores <- ores %>%
  filter(country == "United States")

ores <- ores %>%
  filter(com_type == "M")

ores <-ores %>%
  mutate(commod1 = strsplit(as.character(commod1),",")) %>%
  unnest(commod1)


ores <- ores %>%
  mutate(state = strsplit(as.character(state),",")) %>%
  unnest(state)

ores <- ores %>%
  mutate(state = str_trim(state)) %>%
  mutate(commod1 = str_trim(commod1))

```

```{r top_ores}

top_ores_us <- ores %>%
  group_by(commod1) %>%
  count() %>%
  arrange(desc(n))


colnames(top_ores_us) <- c("Metal", "Number Of Deposits")


  

write.csv(top_ores_us[1:20,],"top_ores_us.csv")
```


```{r}
state_id <- read.csv("state_id.csv")

```

```{r ores_bystate}

ores_state <- ores %>%
  mutate(commod1 = str_trim(commod1)) %>%
  filter(commod1 == "Gold" |commod1 == "Silver" |commod1 =="Copper" |commod1 == "Lead" |commod1 == "Iron") %>%
  
  group_by(state,commod1) %>%
  count()  %>%
  merge(state_id,by = "state", all.y = TRUE)


ores_state <- ores_state[,c(1,2,3,4)]
colnames(ores_state) <- c("state","Metal","Number Of Deposits","id")

write.csv(ores_state,"topdeposits_bystate.csv")

```


```{r ores_bystate}

ores_state <- ores %>%
  mutate(commod1 = str_trim(commod1)) %>%
  group_by(state,commod1) %>%
  count()


ores_state <- ores_state %>%
  group_by(state) %>%
  top_n(10,n)%>%
  merge(state_id,by = "state", all.y = TRUE)


ores_state <- ores_state[,c(1,2,3)]
colnames(ores_state) <- c("state","Metal","Number Of Deposits")

write.csv(ores_state,"alldeposits_bystate.csv")
```

```{r}


```



```{r ores_statemax}

state_group <- ores %>%
  group_by(state,commod1) %>%
  count() 

state_max <- state_group %>%
  group_by(state)%>%
  filter(n == max(n))

state_max <- merge(state_max,state_id,by = "state", all.y = TRUE)

state_max <- state_max[,1:4]
colnames(state_max) <- c("state","Metal","Number Of Deposits","id")

write.csv(state_max,"top_metal.csv")



```





```{r}


write.csv(ores[,c(1,2,3,6,7,9,16)],"ores_short.csv")
```


```{r}
s_c <- ores %>%
  group_by(state)%>%
  count()


```

```{r}
dir.create(temp <- tempfile())
ores[,c(9,2,3)] %>%
  mutate(commod1 = str_trim(commod1)) %>%
  filter(commod1 == "Gold" |commod1 == "Silver" |commod1 =="Copper" |commod1 == "Lead" |commod1 == "Iron") %>%
  group_by(commod1) %>%
  group_walk(~ write.csv(.x, paste0("by_metal_us/",.y$commod1, ".csv")))
  list.files(temp, pattern = "csv$")

```


```{r}
dir.create(temp <- tempfile())
ores %>%
  mutate(commod1 = str_trim(commod1)) %>%
  filter(commod1 == "Gold" |commod1 == "Silver" |commod1 =="Copper" |commod1 == "Lead" |commod1 == "Iron") %>%
  group_by(commod1) %>%
    group_walk(~ write.csv(.x, paste0("metal_groups/",.y$commod1, ".csv")))
list.files(temp, pattern = "csv$")

```


```{r}
dir.create(temp <- tempfile())

vec <- c("Gold", "Silver","Copper","Lead","Iron")
for(i in 1:5){

ores_arr <- ores %>%
  mutate(commod1 = str_trim(commod1)) %>%
  filter(commod1 == vec[i]) %>%
  group_by(state) %>%
  count() %>%
  merge(state_id[,1:2],by = "state",all.y = TRUE) 
  
  
  ores_arr$n[is.na(ores_arr$n)] <- 0
  colnames(ores_arr) <- c("state", "number of Deposits" , "id")
  write.csv(ores_arr ,paste0("metal_groups/",vec[i], ".csv"))
  
}





```
```{r}
ores_test <- ores %>%
  mutate(commod1 = str_trim(commod1)) %>%
  filter(commod1 == "Iron") %>%
  group_by(state) %>%
  count() %>%
  merge(state_id[,1:2],by = "state",all.y = TRUE)
  


```

```{r}
state_matrix <- ores %>%
  filter(commod1 == "Gold" |commod1 == "Silver" |commod1 =="Copper" |commod1 == "Lead" |commod1 == "Iron") %>%
  group_by(state,commod1) %>%
  count()



state_matrix  <- state_matrix %>%
  pivot_wider(names_from = commod1,values_from = n)

state_matrix <- state_matrix 
  

write.csv(state_matrix,"state_matrix.csv")


```

    group_walk(~ write.csv(.x, paste0("metal_groups/",.y$commod1, ".csv")))
list.files(temp, pattern = "csv$")


```{r}

ores<- read.csv("mineral-ores.csv")

ores <- ores %>%
  filter(country == "United States")

ores <- ores %>%
  filter(com_type == "M")



ores <- ores %>%
  mutate(state = strsplit(as.character(state),",")) %>%
  unnest(state)

ores$concat <- paste(ores$commod1,ores$commod2,ores$commod3)
```

```{r}

ores_sep <- ores %>%
  separate(concat,c("A","B","C","D","E"))


```

```{r}
ores_a <- ores_sep %>%
  group_by(A) %>%
  
  count() %>%
  order(desc(n))

ores_b <- ores_sep %>%
  group_by(B) %>%
  count()


ores_c <- ores_sep %>%
  group_by(C) %>%
  count()


ores_d <- ores_sep %>%
  group_by(D) %>%
  count()


ores_e <- ores_sep %>%
  group_by(E) %>%
  count()


```
```{r}

ab <- merge(ores_a,ores_b,by.x = "A", by.y = "B")
abc <- merge(ab,ores_c,by.x = "A", by.y = "C")
abcd <- merge(abc,ores_d,by.x = "A", by.y = "D")
abcde <- merge(abcd,ores_e,by.x = "A", by.y = "E")


abcde <- t(abcde)

write.csv(abcde,"state_matrix.csv")

```

